// Conversion DDL generation — pure. Emits dependency-safe, ordered
// ALTER statements: parents before children (foreign keys), wrapped in
// SET FOREIGN_KEY_CHECKS so charsets never disagree mid-conversion.

/**
 * Topologically sort table objects so FK parents come before children.
 * Falls back to snapshot order for independent tables; tolerates cycles
 * (appends remaining tables in original order).
 */
export function topoSortTables(tables) {
  const names = new Set(tables.map((t) => t.name));
  const dependsOn = new Map(); // child -> Set(parents within the conversion set)
  for (const t of tables) {
    const parents = new Set(
      (t.foreignKeys ?? [])
        .map((fk) => fk.refTable)
        .filter((ref) => ref !== t.name && names.has(ref))
    );
    dependsOn.set(t.name, parents);
  }
  const sorted = [];
  const placed = new Set();
  let progressed = true;
  let remaining = [...tables];
  while (remaining.length > 0 && progressed) {
    progressed = false;
    const next = [];
    for (const t of remaining) {
      const parents = dependsOn.get(t.name);
      if ([...parents].every((p) => placed.has(p))) {
        sorted.push(t);
        placed.add(t.name);
        progressed = true;
      } else {
        next.push(t);
      }
    }
    remaining = next;
  }
  return [...sorted, ...remaining]; // cycle fallback keeps original order
}

/**
 * Generate conversion DDL from a snapshot + analysis (from analyzeSchema).
 * Returns { statements, sql }:
 *  - statements: executable statements only, in order (fed to adapter.execute)
 *  - sql: reviewable script including comments, for convert.sql
 */
export function generateDdl(snapshot, analysis, opts = {}) {
  const targetCharset = analysis.target.charset;
  const targetCollation = analysis.target.collation;

  const needsDbAlter = analysis.findings.some(
    (f) => f.level === 'database' && f.type === 'charset'
  );
  const tableNames = new Set(
    analysis.findings
      .filter((f) => f.type === 'charset' && (f.level === 'table' || f.level === 'column'))
      .map((f) => f.table ?? f.object)
  );
  const tablesToConvert = topoSortTables(
    (snapshot.tables ?? []).filter((t) => tableNames.has(t.name))
  );

  const statements = [];
  const lines = [];
  lines.push(`-- Conversion to ${targetCharset} / ${targetCollation}`);
  lines.push(`-- Generated by @irgendutils/wp-charset-collation-checker${opts.timestamp ? ` at ${opts.timestamp}` : ''}`);
  lines.push('-- Review before running. CONVERT TO rewrites bytes on disk: take a backup first.');
  lines.push('');

  if (statements.length === 0 && !needsDbAlter && tablesToConvert.length === 0) {
    lines.push('-- Nothing to convert: schema already matches the target.');
    return { statements, sql: lines.join('\n') + '\n' };
  }

  if (tablesToConvert.length > 0) {
    statements.push('SET FOREIGN_KEY_CHECKS=0');
    lines.push('SET FOREIGN_KEY_CHECKS=0;');
  }

  if (needsDbAlter && snapshot.database?.name) {
    const stmt = `ALTER DATABASE \`${snapshot.database.name}\` CHARACTER SET ${targetCharset} COLLATE ${targetCollation}`;
    statements.push(stmt);
    lines.push('', '-- Fix the database default so future tables inherit the right charset', `${stmt};`);
  }

  for (const table of tablesToConvert) {
    const stmt = `ALTER TABLE \`${table.name}\` CONVERT TO CHARACTER SET ${targetCharset} COLLATE ${targetCollation}`;
    statements.push(stmt);
    lines.push('', `${stmt};`);
  }

  if (tablesToConvert.length > 0) {
    statements.push('SET FOREIGN_KEY_CHECKS=1');
    lines.push('', 'SET FOREIGN_KEY_CHECKS=1;');
  }

  for (const w of analysis.indexWarnings ?? []) {
    lines.push('', `-- WARNING: ${w.message}`);
  }

  lines.push('', `-- Remember the connection too: clients must use ${targetCharset} (SET NAMES ${targetCharset}),`);
  lines.push('-- or newly written data re-corrupts even after conversion.');

  return { statements, sql: lines.join('\n') + '\n' };
}
