function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeApachePath(str) {
  // Apache Redirect directives can wrap paths in double quotes
  return `"${str.replace(/"/g, '\\"')}"`;
}

function escapeNginxPath(str) {
  // Nginx config allows double quotes
  return `"${str.replace(/"/g, '\\"')}"`;
}

export function exportRules(mapData) {
  let apacheLines = [];
  let nginxRewriteLines = [];
  let nginxMapLines = [];

  apacheLines.push('# ====================================================================');
  apacheLines.push('# Apache Redirect Rules (Generated by @irgendutils/redirect-gen)');
  apacheLines.push('# ====================================================================');
  apacheLines.push('RewriteEngine On');
  apacheLines.push('');

  nginxRewriteLines.push('# ====================================================================');
  nginxRewriteLines.push('# Nginx Individual Rewrite Rules (Generated by @irgendutils/redirect-gen)');
  nginxRewriteLines.push('# ====================================================================');
  nginxRewriteLines.push('');

  nginxMapLines.push('# ====================================================================');
  nginxMapLines.push('# Nginx Map Configuration (Generated by @irgendutils/redirect-gen)');
  nginxMapLines.push('# ====================================================================');
  nginxMapLines.push('# Add this block inside your http {} context, outside server {} blocks:');
  nginxMapLines.push('map $request_uri $redirect_uri {');
  nginxMapLines.push('    default "";');
  nginxMapLines.push('');

  for (const entry of mapData) {
    const src = entry.source;
    let tgt = entry.target;
    const status = entry.status;
    const classification = entry.classification;

    if (!src) continue;
    if (classification === 'missing') continue; // Don't write rules for missing targets

    const hasQuery = src.includes('?');

    // Split query if present
    let srcPath = src;
    let srcQuery = '';
    if (hasQuery) {
      const idx = src.indexOf('?');
      srcPath = src.substring(0, idx);
      srcQuery = src.substring(idx + 1);
    }

    // 1. Apache Rules Generation
    if (status === 410) {
      apacheLines.push(`Redirect 410 ${escapeApachePath(srcPath)}`);
    } else {
      if (hasQuery) {
        // Must use RewriteCond to match Query String
        const escapedPathPattern = escapeRegex(srcPath.replace(/^\//, '')); // Strip leading slash for RewriteRule pattern
        apacheLines.push(`RewriteCond %{QUERY_STRING} ^${escapeRegex(srcQuery)}$`);
        // Append ? at the end of target to discard original query, or append target query
        const queryTerminator = tgt.includes('?') ? '' : '?';
        apacheLines.push(`RewriteRule ^${escapedPathPattern}$ ${tgt}${queryTerminator} [R=${status},L]`);
      } else {
        apacheLines.push(`Redirect ${status} ${escapeApachePath(srcPath)} ${escapeApachePath(tgt)}`);
      }
    }

    // 2. Nginx Rewrite Lines Generation
    if (status === 410) {
      if (hasQuery) {
        nginxRewriteLines.push(`if ($request_uri = ${escapeNginxPath(src)}) {`);
        nginxRewriteLines.push(`    return 410;`);
        nginxRewriteLines.push(`}`);
      } else {
        const escapedPath = escapeRegex(srcPath);
        nginxRewriteLines.push(`rewrite ^${escapedPath}$ "" permanent; # returns gone if configured or rewrite to empty`);
        // Or cleaner:
        // nginxRewriteLines.push(`location = ${srcPath} { return 410; }`);
      }
    } else {
      if (hasQuery || src.includes(' ') || src.includes('"')) {
        // Use exact request_uri match inside if block for safety
        nginxRewriteLines.push(`if ($request_uri = ${escapeNginxPath(src)}) {`);
        // In Nginx return, append ? to target if we want to strip the original query string (and target has no query of its own)
        const queryTerminator = tgt.includes('?') ? '' : '?';
        nginxRewriteLines.push(`    return ${status} ${tgt}${queryTerminator};`);
        nginxRewriteLines.push(`}`);
      } else {
        const escapedPath = escapeRegex(srcPath);
        const permFlag = status === 301 ? 'permanent' : 'redirect';
        nginxRewriteLines.push(`rewrite ^${escapedPath}$ ${tgt} ${permFlag};`);
      }
    }

    // 3. Nginx Map Lines Generation
    const mapVal = status === 410 ? 'gone' : tgt;
    nginxMapLines.push(`    ${escapeNginxPath(src)} ${escapeNginxPath(mapVal)};`);
  }

  nginxMapLines.push('}');
  nginxMapLines.push('');
  nginxMapLines.push('# Inside your server {} block, use this logic to perform the redirects:');
  nginxMapLines.push('# if ($redirect_uri = "gone") {');
  nginxMapLines.push('#     return 410;');
  nginxMapLines.push('# }');
  nginxMapLines.push('# if ($redirect_uri != "") {');
  nginxMapLines.push('#     return 301 $redirect_uri;');
  nginxMapLines.push('# }');

  return {
    apache: apacheLines.join('\n'),
    nginxRewrite: nginxRewriteLines.join('\n'),
    nginxMap: nginxMapLines.join('\n')
  };
}
